### ISSUE TITLE
"exec format error" on henfri/smarthome-ng:latest

### ISSUE THREAD

**Issue by muenzpraeger** [smarthomeNG/docker#5]
I'm not sure if this is the correct repo for opening this issue. 

When installing the `latest` image on docker hub I'm getting a `standard_init_linux.go:211: exec user process caused "exec format error"` exception when the container gets started.

Same applies when I build locally, based on the current Dockerfile in the `develop` branch.

Sidenote: I had to add `libatlas-dev` as another package for the local build.

I’m using Raspbian as OS on my Pi.

**Comment by henfri** [comment]
Hello,

you are trying to run an amd64 docker on an raspberry pi. That cannot work.
You can try to build (and I think that you did that). But then you need to start with a linux distribution in the first line of the docker file that also runs on the raspi cpu. 

Greetings,
Hendrik

**Comment by muenzpraeger** [comment]
“Wer lesen kann...” - thanks! ;-)

Still not running, as there’s also a dependency issue with `libatlas`. I’ll stick with 1.4 then for now.
